"""Initial six-table schema and forced tenant row-level security.

Revision ID: 0001_initial
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("wecom_corp_id", sa.String(length=128), nullable=False),
        sa.Column("wecom_external_user_id", sa.String(length=256), nullable=False),
        sa.Column("display_name", sa.String(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("vector_store_id", sa.String(length=256), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("vector_store_id", name=op.f("uq_users_vector_store_id")),
        sa.UniqueConstraint(
            "wecom_corp_id",
            "wecom_external_user_id",
            name=op.f("uq_users_wecom_corp_id_wecom_external_user_id"),
        ),
    )
    op.create_table(
        "conversations",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("open_kfid", sa.String(length=256), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_conversations_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("user_id", "id", name=op.f("uq_conversations_user_id_id")),
    )
    op.create_index(
        "ix_conversations_user_created", "conversations", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "sources",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("wechat_msg_id", sa.String(length=256), nullable=True),
        sa.Column(
            "source_type",
            sa.Enum(
                "note",
                "image",
                "pdf",
                "word",
                "excel",
                "ppt",
                "audio",
                "video",
                "web_page",
                "wechat_article",
                "wechat_channel",
                "other",
                name="source_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=True),
        sa.Column("storage_key", sa.String(length=1024), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "processing",
                "ready",
                "metadata_only",
                "failed",
                "deleting",
                "deleted",
                name="source_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="received",
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("vector_file_id", sa.String(length=256), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_sources_valid_sha256")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_sources_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint("user_id", "id", name=op.f("uq_sources_user_id_id")),
        sa.UniqueConstraint(
            "user_id", "wechat_msg_id", name=op.f("uq_sources_user_id_wechat_msg_id")
        ),
    )
    op.create_index("ix_sources_user_created", "sources", ["user_id", "created_at"], unique=False)
    op.create_index(op.f("ix_sources_vector_file_id"), "sources", ["vector_file_id"], unique=False)
    op.create_index(
        "uq_sources_user_sha256_active",
        "sources",
        ["user_id", "sha256"],
        unique=True,
        postgresql_where=sa.text("sha256 IS NOT NULL AND status <> 'deleted'"),
    )
    op.create_table(
        "assets",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "original",
                "normalized",
                "audio",
                "keyframe",
                "transcript",
                name="asset_kind",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=True),
        sa.Column("content_type", sa.String(length=256), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_assets_valid_sha256")
        ),
        sa.CheckConstraint("size_bytes >= 0", name=op.f("ck_assets_nonnegative_size")),
        sa.ForeignKeyConstraint(
            ["user_id", "source_id"],
            ["sources.user_id", "sources.id"],
            name=op.f("fk_assets_user_id_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_assets_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("user_id", "storage_key", name=op.f("uq_assets_user_id_storage_key")),
    )
    op.create_index("ix_assets_user_source", "assets", ["user_id", "source_id"], unique=False)
    op.create_table(
        "ingestion_jobs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "downloading",
                "parsing",
                "transcribing",
                "indexing",
                "completed",
                "failed",
                name="job_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="queued",
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default="3", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status <> 'failed' OR (error_message IS NOT NULL AND length(trim(error_message)) > 0)",
            name=op.f("ck_ingestion_jobs_failed_requires_error"),
        ),
        sa.CheckConstraint(
            "attempts >= 0 AND max_attempts > 0", name=op.f("ck_ingestion_jobs_valid_attempts")
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "source_id"],
            ["sources.user_id", "sources.id"],
            name=op.f("fk_ingestion_jobs_user_id_sources"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_ingestion_jobs_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_jobs")),
    )
    op.create_index(
        "ix_ingestion_jobs_user_status_retry",
        "ingestion_jobs",
        ["user_id", "status", "next_retry_at"],
        unique=False,
    )
    op.create_table(
        "messages",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("conversation_id", sa.Uuid(), nullable=False),
        sa.Column("wechat_msg_id", sa.String(length=256), nullable=True),
        sa.Column(
            "role",
            sa.Enum(
                "user",
                "assistant",
                "system",
                name="message_role",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("message_type", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "conversation_id"],
            ["conversations.user_id", "conversations.id"],
            name=op.f("fk_messages_user_id_conversations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_messages_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "user_id", "wechat_msg_id", name=op.f("uq_messages_user_id_wechat_msg_id")
        ),
    )
    op.create_index(
        "ix_messages_user_conversation_created",
        "messages",
        ["user_id", "conversation_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###

    op.execute("GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO pkb_app")
    op.execute("REVOKE ALL ON alembic_version FROM pkb_app")
    op.execute("GRANT SELECT ON alembic_version TO pkb_app")
    for table in ("users", "sources", "assets", "conversations", "messages", "ingestion_jobs"):
        column = "id" if table == "users" else "user_id"
        tenant = "NULLIF(current_setting('app.user_id', true), '')::uuid"
        op.execute(f'ALTER TABLE "{table}" ENABLE ROW LEVEL SECURITY')
        op.execute(f'ALTER TABLE "{table}" FORCE ROW LEVEL SECURITY')
        op.execute(
            f'CREATE POLICY tenant_isolation ON "{table}" '
            f"USING ({column} = {tenant}) WITH CHECK ({column} = {tenant})"
        )


def downgrade() -> None:
    for table in ("ingestion_jobs", "messages", "assets", "sources", "conversations", "users"):
        op.drop_table(table)
